### ISSUE TITLE
MaxListenersExceededWarning

### ISSUE THREAD

**Issue by Morb0** [fjodor-rybakov/discord-nestjs#1002]
**Describe the bug**
After registering another command, start receiving NodeJS warning:
`(node:87859) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 interactionCreate listeners added to [Client]. Use emitter.setMaxListeners() to increase limit`
In total now have 13 commands (methods annotated with `@Handler()`).
As I understand it, a listener is created for each command. If this is the expected behavior, maybe it should call `setMaxListeners` for the Discord client during initialization.

**To Reproduce**

1. Register 13 commands
2. See warning

**Expected behavior**
No warning

**Desktop (please complete the following information):**

- OS: MacOS Ventura 13.1

**Comment by fjodor-rybakov** [comment]
Hi! You can set `setMaxListeners` to your liking or turn off the warning altogether by setting it to 0. 
This can be done in `setupClientFactory`.

Example:
```ts
@Module({
  imports: [
    ConfigModule.forRoot(),
    DiscordModule.forRootAsync({
      imports: [ConfigModule],
      useFactory: (configService: ConfigService) => ({
        token: configService.get('TOKEN'),
        discordClientOptions: {
          intents: [GatewayIntentBits.Guilds, GatewayIntentBits.GuildMessages],
        },
        registerCommandOptions: [
          {
            forGuild: configService.get('GUILD_ID_WITH_COMMANDS'),
            removeCommandsBefore: true,
          },
        ],
        failOnLogin: true,
      }),
      setupClientFactory: (client: Client) => {
        client.setMaxListeners(30);
      },
      inject: [ConfigService],
    }),
    BotModule,
  ],
})
export class AppModule {}
```

**Comment by Spythere** [comment]
Setting max listeners is very ineffictient... What's the better way to resolve the problem if I have more than 10 commands and don't necesarrily want to add new event emitters?

**Comment by Prochy20** [comment]
I got to the very same situation.
