### ISSUE TITLE
Restrict slash command visibility by role

### ISSUE THREAD

**Issue by jacopo-degattis** [fjodor-rybakov/discord-nestjs#1005]
Hi, I'm currently developing a bot using this awesome library but I stumbled upon a problem.
I would like to restrict a slash command visibility only to certain users having a specific Role.

I was wondering if there's a way I can do it or if it's a feature to be developed.

I saw that right now I can only restrict by permission but I would like to the same with roles.

I've considered to show the command also to members that don't have the permission and then if they try to execute it
tell them they can't but it doesn't seem as clean as not showing the command at all.

Thank you so much

**Comment by fjodor-rybakov** [comment]
Hi! As far as I know, it is impossible to hide the slash command from the user in Discord

**Comment by jacopo-degattis** [comment]
Oh I see, I think I'll go with manual checking to forbid command to unauthorized members.
Thank you for the quick reply
