### ISSUE TITLE
Revoking permissions in channel

### ISSUE THREAD

**Issue by jacopo-degattis** [fjodor-rybakov/discord-nestjs#1009]
Hi everyone,

I'm trying to disable permissions for a specific role inside a channel
I want to deny the 'ADD_REACTION' permission to the @everyone role.
Right now I'm using the following command:

`await currentVoiceChannel.permissionOverwrites.create(clientEvent.guild.roles.everyone, { AddReactions: false });`

I execute the above command just before replying from the bot side.
If I try to react using a random user (even not an admin one) it keeps let me add reactions.

I don't understand if I have to use a different `permissionOverwrites` method such as `edit` or `delete` or if I'm doing something else wrong.

Let me know
Thank you so much

**Comment by fjodor-rybakov** [comment]
Hi! Try to asking an issue in this repository https://github.com/discordjs/discord.js/issues
