### ISSUE TITLE
Attachment Param

### ISSUE THREAD

**Issue by T0pN1ck** [fjodor-rybakov/discord-nestjs#1012]
Hello. Why i cant get additional parameters attachments (url, proxyUrl, etc.), but only id?
![image](https://user-images.githubusercontent.com/88724799/220955367-d8d96892-fe62-4f3e-9c61-439d48fccffb.png)
![image](https://user-images.githubusercontent.com/88724799/220955536-65da6335-2d61-4df3-be1b-b986ad486aa1.png)
![image](https://user-images.githubusercontent.com/88724799/220955674-84f68e09-2f2b-4f7c-806f-90f7d1ccee7b.png)
Its problem with me or type of return?)

**Comment by fjodor-rybakov** [comment]
Looks like `attachment` is not in `value`

**Comment by T0pN1ck** [comment]
hm...

**Comment by T0pN1ck** [comment]
А теперь на русском, почему же так?)

**Comment by fjodor-rybakov** [comment]
> А теперь на русском, почему же так?)

https://github.com/fjodor-rybakov/discord-nestjs/blob/master/packages/common/src/pipe/slash-command/slash-command.pipe.ts#L55 вот в этой строке всегда берётся `value`. И `value` всегда примитив. Если нужен объект, то надо брать значение из `attachment`. В принципе по ожидаемому типу я могу попробовать угадать, что тебе нужен именно объект, а не примитив

**Comment by T0pN1ck** [comment]
Может быть тогда сразу объект выдавать?

**Comment by fjodor-rybakov** [comment]
> Может быть тогда сразу объект выдавать?

Это breaking change и плюсом надо понять как быть с class-transform, потому что при трансформе он пытается по типу класса воссоздать экземпляр

**Comment by fjodor-rybakov** [comment]
Was added in @discord-nestjs/common 5.2.0
