### ISSUE TITLE
UseCollectors on command results in missing constructor

### ISSUE THREAD

**Issue by foestauf** [fjodor-rybakov/discord-nestjs#1057]
When I have the UseCollectors decorator on a command class it appears my constructor is not being initialized. All values inside are undefined and I do not see a console log I put in the constructor method.

**To Reproduce**

1. Have a Command class with a UseCollectors decorator.
2. Reference the CollectorClass in the constructor of the command class.

**Expected behavior**
Constructor initializes.

**Screenshots**

On common 5.2.3 and core 5.3.5.
Reproduction: https://github.com/foestauf/discordjs-bug

**Comment by fjodor-rybakov** [comment]
Hi! I can't reproduce your problem. Make sure you add your providers to module. Also look at samples https://github.com/fjodor-rybakov/discord-nestjs/tree/master/packages/sample/interaction-collector Probably this will help you to find issue

**Comment by foestauf** [comment]
I missed an important part in the bug description. I have updated it and included a reproducible repo.

**Comment by foestauf** [comment]
I think the issue here is it's creating a circular dependency. Going to close the issue.
