### ISSUE TITLE
The dto variable is returned to undefined

### ISSUE THREAD

**Issue by junjielyu13** [fjodor-rybakov/discord-nestjs#1065]
Hello, I have encountered a little problem:

When I want to get the variable input by the user from the discord command line, it returns undefined

**Version**
![image](https://user-images.githubusercontent.com/74879056/235980236-6daf054d-f44e-40d0-ba52-11396db31988.png)

**Screenshots**

**command.ts**
![image](https://user-images.githubusercontent.com/74879056/235980495-def0eebc-a4e7-48fc-a643-4276800ec535.png)

**dto.ts**
![image](https://user-images.githubusercontent.com/74879056/235980686-e3699f32-d723-4137-9314-19280142b158.png)

**output on log**
![image](https://user-images.githubusercontent.com/74879056/235980780-98bb3acd-5422-4bb8-b7af-7bbbad06cf63.png)

**output on discord**
![image](https://user-images.githubusercontent.com/74879056/235980897-9531ba45-ba64-47a3-a709-2fd4bc957043.png)

**Comment by fjodor-rybakov** [comment]
Hi! [Make sure](https://github.com/fjodor-rybakov/discord-nestjs/tree/master/packages/core#:~:text=%E2%9A%A0%EF%B8%8F,tsconfig.json.), please

**Comment by junjielyu13** [comment]
It solve, Thanks, I'm just dumb. I have been calling the command line of the history record, and the result is that the command line of the history record is an old version that has not been updated. I have to rewrite a command line to use it.
