### ISSUE TITLE
TS error with set strictNullChecks to true

### ISSUE THREAD

**Issue by its-monotype** [fjodor-rybakov/discord-nestjs#1073]
**Describe the bug**
when using
@InjectDiscordClient()
private readonly client: Client,
with strictNullChecks: true,
TS error appears: Unable to resolve signature of parameter decorator when called as an expression.
  Argument of type 'undefined' is not assignable to parameter of type 'string | symbol'.ts(1239)

**To Reproduce**
set "strictNullChecks": true, in tsconfig.json
use: @InjectDiscordClient()
    private readonly client: Client,
 in service

**Comment by fjodor-rybakov** [comment]
Hi! Update to latest, please
 - @discord-nestjs/common@5.2.5
 - @discord-nestjs/core@5.3.7

**Comment by its-monotype** [comment]
@fjodor-rybakov Thanks, works like a charm
