### ISSUE TITLE
The bot doesn't want to "launch"

### ISSUE THREAD

**Issue by Jules010209** [fjodor-rybakov/discord-nestjs#1089]
Hi, it's me again and I've still got a problem. I'm currently working on a project to implement a bot in a rather large API. I have a ready event in my gateway that sends a message to the console, but when I run the API nothing happens about this event. However, the event is loaded and the commands are recorded. To see if it wasn't a specific problem, I generated a blank project and tested it, and it worked. So I'm asking for your help! Thank you

**Comment by fjodor-rybakov** [comment]
Hi! Check intents please https://discordjs.guide/popular-topics/intents.html#privileged-intents

**Comment by Jules010209** [comment]
Already here :/
![image](https://github.com/fjodor-rybakov/discord-nestjs/assets/67187964/d0fc2642-5447-47e7-becc-9b13d4dae73e)
![image](https://github.com/fjodor-rybakov/discord-nestjs/assets/67187964/7b02e697-ab00-41a0-92a0-6e44580cdb13)
