### ISSUE TITLE
Add paramType CHANNEL (command options)

### ISSUE THREAD

**Issue by Blamo27** [fjodor-rybakov/discord-nestjs#1096]
Hello,

Unless I am mistaken there is no CHANNEL ParamType for command options, can you please add it ?
Thanks.

https://github.com/fjodor-rybakov/discord-nestjs/blob/master/packages/core/src/definitions/types/param.type.ts

DiscordJS, channel type is available : 
https://discordjs.guide/slash-commands/advanced-creation.html#option-types

**Comment by Blamo27** [comment]
My bad i found that param @Channel exists.

**Comment by Elias177Dev** [comment]
sorry i dont understand how i can use that. Can someone explain it ? Cause i want to tag a Channel in the command
