### ISSUE TITLE
Command Decorator sets default member permissions to administrator

### ISSUE THREAD

**Issue by rahul-webd** [fjodor-rybakov/discord-nestjs#1102]
**Describe the bug**
When using the command decorator and not setting the *defaultMemberPermissions* field to any bit field, it sets the default member permission required as *Administrator*, causing members to not able to use the command at all.

**To Reproduce**

1. Create a command using the Command Decorator.
2. Do not set any *defaultMemberPermissions* on it.
3. Go to your guild and test the command.
4. Only the member with *administrator* permission will be able to use the command.

**Expected behavior**
When creating any command, every member should be able to use the command.

**Screenshots**
Here, the command decorator is used.

![image](https://github.com/fjodor-rybakov/discord-nestjs/assets/48341496/321ed99c-c08a-419c-807f-a3f768412102)

And here it can be seen that it set a default permission - 

![image](https://github.com/fjodor-rybakov/discord-nestjs/assets/48341496/bd2776bc-3d1d-4093-b7b2-62a28a120136)

Specifically Admin Permission - 

![image](https://github.com/fjodor-rybakov/discord-nestjs/assets/48341496/545855c1-0454-425c-9bcb-61f004907a47)

**Additional context**

If the *defaultMemberPermission* is set to null, then it fixes the problem. Either not passing anything to it, makes it pass 0 which sets the default permission required as admin, or passing *undefined* itself makes it require the admin permission.

**Comment by fjodor-rybakov** [comment]
Hi! This is default behavior for discord.js https://discordjs.guide/slash-commands/permissions.html#member-permissions. If you really want to change this, wrap `@Command` decorator with your own
