### ISSUE TITLE
Slash command params doesn't work with `swc` builder

### ISSUE THREAD

**Issue by Mnigos** [fjodor-rybakov/discord-nestjs#1109]
**Describe the bug**
Using `InteractionEvent` decorator with DTO doesn't work with `swc` builder

**To Reproduce**
Set `swc` builder in your `nest-cli.json`
```json
{
  "$schema": "https://json.schemastore.org/nest-cli",
  "collection": "@nestjs/schematics",
  "sourceRoot": "src",
  "compilerOptions": {
    "builder": "swc",
    "typeCheck": true,
    "tsConfigPath": "tsconfig.json"
  }
}
```

`play.command.ts`
```ts
import { SlashCommandPipe } from '@discord-nestjs/common'
import {
  Command,
  EventParams,
  Handler,
  InteractionEvent,
} from '@discord-nestjs/core'
import { ClientEvents } from 'discord.js'

import { PlayDto } from '../dto/play.dto'

@Command({
  name: 'play',
  description: 'Plays a song',
})
export class PlayCommand {
  @Handler()
  onPlayCommand(
    @InteractionEvent(SlashCommandPipe) dto: PlayDto,
    @EventParams() arguments_: ClientEvents['interactionCreate']
  ): string {
    console.log('DTO', dto)
    console.log('Event args', arguments_)

    return `Start playing ${dto.song}.`
  }
}
```

`play.dto.ts`
```ts
import { Param } from '@discord-nestjs/core';
import { Transform } from 'class-transformer';

export class PlayDto {
  @Transform(({ value }) => value.toUpperCase())
  @Param({
    name: 'song',
    description:
      'Name or URL of song/playlist. Could be from (Youtube, Spotify, SoundCloud)',
    required: true,
  })
  song: string;
}
```

**Expected behavior**
Should work with `swc`, `webpack` and `tsc`

**Screenshots**
### With `swc`
<img width="350" alt="Screenshot 2023-08-22 at 12 16 58" src="https://github.com/fjodor-rybakov/discord-nestjs/assets/56691628/4f7ce0c2-0ace-4b82-891b-fed913917911">
<img width="726" alt="Screenshot 2023-08-22 at 12 17 18" src="https://github.com/fjodor-rybakov/discord-nestjs/assets/56691628/b09efbc2-6c12-43ec-94a4-9fec82117412">

### Without `swc`

<img width="283" alt="Screenshot 2023-08-22 at 12 19 05" src="https://github.com/fjodor-rybakov/discord-nestjs/assets/56691628/5afe5932-4a96-4797-a6c0-85f019b139e1">
<img width="722" alt="Screenshot 2023-08-22 at 12 19 10" src="https://github.com/fjodor-rybakov/discord-nestjs/assets/56691628/112972dc-b700-411f-83b5-cefb953a2ece">

**Comment by fjodor-rybakov** [comment]
@Mnigos can you share your `.swcrc` config?

**Comment by fjodor-rybakov** [comment]
Works fine

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "decorators": true,
      "dynamicImport": true
    },
    "transform": {
      "useDefineForClassFields": true
    },
    "target": "es2022"
  }
}

```

**Comment by Mnigos** [comment]
with
```json
"transform": {
      "useDefineForClassFields": true
    },
```
works fine.
