### ISSUE TITLE
Type Mismatch when using @Param Decorator with type: ParamType.USER

### ISSUE THREAD

**Issue by flo025** [fjodor-rybakov/discord-nestjs#1151]
**Is your feature request related to a problem? Please describe.**
Maybe related to #888 
When I define a User type using the @Param decorator, it is being treated as a string instead of a User object. For example:
```
@Param({
  name: 'user',
  type: ParamType.USER,
})
user: User;
```

**Describe the solution you'd like**
I would like the @Param decorator to correctly interpret and assign the User type, instead of treating it as a string. This will ensure that the parameter behaves as expected when used in the code, retaining all properties and methods of a User object .
(@Param decorator of type Attachment correct apply type)

**Describe alternatives you've considered**
Manually cast the string to User

**Comment by fjodor-rybakov** [comment]
Hi! discord js return user id string, not user object. If you need transform user id to object just write another one pipe in chain
```ts
@InteractionEvent(SlashCommandPipe, AnotherOneTransformPipe)
```
