### ISSUE TITLE
Nest can't resolve dependencies of the SlashCommandPipe

### ISSUE THREAD

**Issue by ArtemOsuskyi** [fjodor-rybakov/discord-nestjs#1153]
**Describe the bug**
Starting an app causes Nest to throw an error ``Nest can't resolve dependencies of the SlashCommandPipe (?, __class_transformer_options__). Please make sure that the argument ReflectMetadataProvider at index [0] is available in the BotModule context.`` during startup. Using NestJS version from ``@discord-nestjs/schematics:application`` template (v10.0.0)

```
import { EventParams, Handler, IA, SubCommand } from '@discord-nestjs/core';
import { ClientEvents } from 'discord.js';

import { SlashCommandPipe } from '@discord-nestjs/common';
import { CreateQuestDto } from '../../dto/create-quest.dto';

@SubCommand({
  name: 'create',
  description: 'Plays a song',
})
export class QuestCreateSubCommand {
  @Handler()
  questCreate(
    @IA(SlashCommandPipe) createQuestDto: CreateQuestDto,
    @EventParams() args: ClientEvents['interactionCreate'],
  ): string {
    console.log(createQuestDto);
    console.log(args);

    return 'Quest created';
  }
}

```

**Tried to do so far**
- Import ReflectMetadataProvider as a provider in BotModule

**To Reproduce**

1. Pass ``@InteractionEvent(SlashCommandPipe)`` in any command params.
2. Run ``npm run start:dev``

**Comment by fjodor-rybakov** [comment]
Hi! Try to add `DiscordModule.forFeature()` to module imports

**Comment by fjodor-rybakov** [comment]
Check that you only have 1 version of the library installed in the repository

**Comment by ArtemOsuskyi** [comment]
Reinstalled ``@discord-nestjs/core`` and ``@discord-nestjs/common`` and issue got fixed. Thank you, sorry for the inconvenience!
