### ISSUE TITLE
CommandInteraction undefined

### ISSUE THREAD

**Issue by Elias177Dev** [fjodor-rybakov/discord-nestjs#1200]
Hey,

when i us the `CommandInteraction` and `@InteractionEvent(SlashCommandPipe)` at the same time the `CommandInteraction` is `undefined`
Is there a way to fix it? Cause i need both.

My code:
`async onPollCommand(interaction: CommandInteraction, @InteractionEvent(SlashCommandPipe) options: DcPollDto): Promise<void> {`

**Comment by fjodor-rybakov** [comment]
Hi! Yes, you can
```ts
async onPollCommand(@InteractionEvent() interaction: CommandInteraction, @InteractionEvent(SlashCommandPipe) options: DcPollDto): 
```
