### ISSUE TITLE
Repeat Bot Messages Reply On Message Event 

### ISSUE THREAD

**Issue by shubhamR1997** [fjodor-rybakov/discord-nestjs#26]
**Describe the bug**
The "message" event suppose to reply one time but the bot is replying two times even the (!message.author.bot) condition is checked still it replies two times.

**To Reproduce**
1. Setup the "message" event
2. send a message

**Expected behavior**
The bot should reply one time only instead of repeating twice. 

**Screenshots**
![image](https://user-images.githubusercontent.com/24357511/97866935-e3a8e880-1d32-11eb-94ac-1bc865261d3f.png)

**Comment by fjodor-rybakov** [comment]
Try this or provide a minimal repository for replay
```typescript
@Injectable()
export class BotGateway {
  @On({event: 'message'})
  async onMessage(message: Message): Promise<void> {
    if (!message.author.bot) {
      await message.reply('I\'m watching you');
    }
  }
}
```
This work for me
![image](https://user-images.githubusercontent.com/23727801/97879486-194cd200-1d31-11eb-8c6f-2c0980ff6ff4.png)

**Comment by shubhamR1997** [comment]
only difference is I am using @Controller() annotation instead of @Injectable else all code is same. I was trying this example only. The doc mention we can use any of annotation right

**Comment by fjodor-rybakov** [comment]
Yes, it works too
![image](https://user-images.githubusercontent.com/23727801/97882733-fc1a0280-1d34-11eb-8a70-18d56faf44aa.png)
![image](https://user-images.githubusercontent.com/23727801/97882764-076d2e00-1d35-11eb-91d7-beedf91a565b.png)

**Comment by shubhamR1997** [comment]
Really not sure wts wrong with mine way of doing can you see.

![image](https://user-images.githubusercontent.com/24357511/97979812-d274e000-1df5-11eb-9a7c-f11239e73bcc.png)


![image](https://user-images.githubusercontent.com/24357511/97979834-dc96de80-1df5-11eb-85b3-0b07696860f1.png)

it's like this replying two times.

**Comment by shubhamR1997** [comment]
Sorry it's just not this everything is coming two times...that ready event also firing two times...

**Comment by fjodor-rybakov** [comment]
This is possible only if you have announced twice a subscription to the "message" or "ready" event.
Like this: 
![image](https://user-images.githubusercontent.com/23727801/98019825-483b7480-1e13-11eb-9a66-5bff0eac9452.png)
Check your code pls

**Comment by shubhamR1997** [comment]
Ok sorry, It was a problem with my code. I was declaring the bot controller in controller too causing it to run two times. We can close the issue. Thanks
