### ISSUE TITLE
Add ReactionsCollector and MessagesCollector

### ISSUE THREAD

**Issue by idkDemo** [fjodor-rybakov/discord-nestjs#277]
Hey ! I'm thinking about how implementing collectors.
We could use it like that once implemented

> in the file: myReactionCollector.class.ts
```typescript
@ReactionColletor({
  reactions: ["✋"], // an array with all reactions needed;
  deleteOnReply: true, // if true, the user's reaction will automatically deleted;
  authorizeBot: false, // if true, bots can add reactions;
  endTime: 5000 // (in ms) A timer for stop the ReactionCollector;
})
export class MyReactionColletor {

  @OnReaction("✋")
  async doSomething(context: ReactionContext): Promise<void>{
    this.message.edit("Hahaha !");
    this.resetTimer();
    return; 
  }

}

```

> in the file:  bot.gateway.ts
```typescript
@Injectable()
export class BotGateway {

  constructor(
    private readonly DiscordClient: DiscordClientProvider,
  ) { }

  @OnCommand('hey')
  async onCommand(
    @Content() content: UserDto,
    @Context() [context]: [Message],
    @UseReactionCollector(MyReactionColletor) reactionCollector // create an instance of the ReactionCollector;
  ): Promise<void> {
    var message = await context.channel.send("Heyy ! Give me a high five ! ");
    reactionCollector.setMessage(message) // Start the ReactionCollector;
    return; 
  }

}
```
I don't know if this is enough, I am only offering a usecase. If it's interesting I could do more work to implement it :)
This can work with MessageColletor.
Tell me what do you think about that ? ^^

edit: **07/04/21**

_to do:_

- [x] Implement ReactionCollector decorator `@ReactionCollector`.
- [x] Implement ReactionCollector resolver and provider.
- [ ] Implement OnReaction decorator `@OnReaction`.
- [ ] Implement OnReaction resolever.
- [ ] Implement UseReactionCollector decorator `@UseReactionCollector`.
- [ ] Implement UseReactionCollector resolver.
- [ ] TEST
- [ ] Implement MessageCollector decorator `@MessageCollector`.
- [ ] Implement MessageCollector resolver and provider.
- [ ] Implement OnMessage decorator `@OnMessage`.
- [ ] Implement OnMessage resolever.
- [ ] Implement UseMessageCollectorDecorator `@UseMessageCollector`.
- [ ] Implement UseMessageCollectorDecorator resolever.
- [ ] TEST
- [ ] Update the doc.

**Comment by fjodor-rybakov** [comment]
Great idea! 
But what mean class `AbstractDiscordReactionCollector`? What is this for?
Also need to think about how to handle the timeout

**Comment by fjodor-rybakov** [comment]
And did I understand correctly that you want to implement this feature yourself? 🙂 If not, then I can release the patch myself within a month

**Comment by idkDemo** [comment]
The `AbstractDiscordReactionCollector` is a class that handle the Discord.js ReactionCollector class, and implement methodes that we can need like resetTimer() or stuff like that. I don't know what is the best way between extends a class or use an injection I'm still thinking about that 🤔 
And yes I can work on it ! I have some idea of how implement this 😊 I can try somethings. (I never work with decorators but  it seems to be not so hard 🙃)
