### ISSUE TITLE
Lib doesn't accept prefixes with space

### ISSUE THREAD

**Issue by henriqueleite42** [fjodor-rybakov/discord-nestjs#292]
**Describe the bug**
When a prefix with a space in it is passed to the `commandPrefix` prop, the lib can't recognize it and doesn't call any command.

**To Reproduce**
1. Create a simple bot using this lib (you can use the [01-hello-bot-app](https://github.com/fjodor-rybakov/discord-nestjs/tree/master/sample/01-hello-bot-app))
2. Set the prefix as something like `"prefix "`
3. See error

**Expected behavior**
It was expected that the lib can handle prefixes with space.

**Screenshots:**
![image](https://user-images.githubusercontent.com/50992814/115604226-82141080-a2b7-11eb-99cc-8b7d0ddbc6d1.png)

**Additional context**
thanks for the awesome lib! Apart from this problem, I am really loving it, it is very good to be able to create bots with an organized architecture.

**Comment by henriqueleite42** [comment]
I think I may found the cause of this bug, so I made PR #293.

**Comment by fjodor-rybakov** [comment]
Thanks for contributing! Fix please one comment
