### ISSUE TITLE
Usage with discord-buttons

### ISSUE THREAD

**Issue by xKamaiL** [fjodor-rybakov/discord-nestjs#448]
How to usage with this https://www.npmjs.com/package/discord-buttons

![image](https://user-images.githubusercontent.com/12003208/128622016-3ccc44fb-10cb-4b61-8cc9-c14dad13ded7.png)

We want to do like disbut(client); 
i have try on onReady event but it doesn't work!

**Comment by fjodor-rybakov** [comment]
Hi! Provide a minimal repository for reproduce please
