### ISSUE TITLE
How to use with ShardingManager

### ISSUE THREAD

**Issue by xKamaiL** [fjodor-rybakov/discord-nestjs#467]
https://discordjs.guide/sharding/#when-to-shard

**Comment by KieronWiltshire** [comment]
Why was this closed? I'm curious as to how you would use this with sharding? Is it just supported out of the box?

**Comment by xKamaiL** [comment]
Its not support sharing

**Comment by KieronWiltshire** [comment]
@xKamaiL I wrote up a small guide on how to get sharding to work with this package [here](https://github.com/fjodor-rybakov/discord-nestjs/issues/911).
