### ISSUE TITLE
Cannot Execute Command

### ISSUE THREAD

**Issue by cagrisungur** [fjodor-rybakov/discord-nestjs#488]
Hello there.

I can not execute commands that i created with command.ts.

`const command = await this.discordProvider
      .getClient()
      .application.commands.fetch(commandId, { guildId: interaction.guildId });`

`command.execute('message', args);`

Execute is undefined. 

So i used  `.fetch` function as a replace official command get method.

**Comment by fjodor-rybakov** [comment]
Sorry, but at the moment this package only works with version 12, 13 is in progress

**Comment by cagrisungur** [comment]
> Sorry, but at the moment this package only works with version 12, 13 is in progress

Okay. Btw thanks for this great package for nestJS.
