### ISSUE TITLE
@Once decorator is running only one time

### ISSUE THREAD

**Issue by chanphiromsok** [fjodor-rybakov/discord-nestjs#490]
**Describe the bug**
when I start the message first-time function inside @Once is execute but the second time it seems. not work at alll

**Code**
```
@Once({ event: 'message' })
  async start(message: Message) {
    if (!message.content.startsWith(prefix)) return;
    if (message.author.bot) return;
    if (!message.member.voice.channel) {
      await message.reply(
        `You need to join voice server bruh **${message.author.username}** :unamused:  `,
      );
      return;
    }
    const per = message.member.voice.channel.permissionsFor(
      message.client.user,
    );
    if (!per.has('CONNECT') || !per.has('SPEAK')) {
      return message.channel.send(
        'I need the permissions to join and speak in your voice channel!',
      );
    }
    const serverQueue = this.queue.get(message.guild.id) as QueueContruct;
    const content = message.content.split(' ');
    const cmd = (content[0] as Cmd) || '';
    const url = content[1] || '';
    this.discordProvider.getClient().on('message', async (message) => {
      console.log(message.author.username);
    });

    if (cmd === '!play') {
      console.log({ cmd });
      this.execute(message, url, serverQueue);
    } else if (cmd === '!skip') {
      this.skipMusic(message, serverQueue);
    } else {
      message.channel.send('You need to enter a valid command!');
    }
  }

```

**Expected behavior**
I expected when I start message in discord if cmd equal to "!play" or "!skip" it should re-run,
should not run only one time.

**Desktop**
 - OS: MacOS BigSur 11.5.1
 - Version [1.2.1]

**Comment by fjodor-rybakov** [comment]
Use [@On](https://medic-group.ru/health/kista.php#:~:text=%D0%92%D1%8B%D0%B6%D0%B8%D0%B4%D0%B0%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F%20%D1%82%D0%B0%D0%BA%D1%82%D0%B8%D0%BA%D0%B0) instead [@Once](https://github.com/fjodor-rybakov/discord-nestjs#%E2%84%B9%EF%B8%8F-once-)

**Comment by fjodor-rybakov** [comment]
Use [@On](https://github.com/fjodor-rybakov/discord-nestjs#%E2%84%B9%EF%B8%8F-on-) instead [@Once](https://github.com/fjodor-rybakov/discord-nestjs#%E2%84%B9%EF%B8%8F-once-)

**Comment by chanphiromsok** [comment]
Thank you Now It works when you upgrade discord.js to version13 ?
