### ISSUE TITLE
Feat: Create custom schematics to allow creating common classes (ex.: commands) from @nestjs/cli

### ISSUE THREAD

**Issue by V-ed** [fjodor-rybakov/discord-nestjs#542]
## Describe the solution you'd like

Creating a custom collection for @nestjs/cli would mean allowing running commands like `npx nest generate command hello-world`, which could create a command with all the imports already there and a basic "not implemented" handler.

Interesting cases for such generations :

- Commands
- Pipes
- Guards
- Exception filters
- Middlewares
- Gateways
   - a basic gateway with a single `@Once('ready')` handler, like given in the examples would suffice
- DTO
    - a basic DTO with a single parameter to give an example with imports already present

---

I do believe this means create a new package, and frankly I've never created a generator / schematic so I don't know what kind of complexity it implies...

---

Obviously copy pasting commands, dtos, pipes, and other generic code works, but having a proper first hand generator would be quite interesting!

**Comment by arelstone** [comment]
This would be so amazing to have.. I am missing this too

**Comment by fjodor-rybakov** [comment]
I think for starters it would be nice to generate projects from samples
