### ISSUE TITLE
Command Payload and interaction not resolving properly

### ISSUE THREAD

**Issue by jordykoppen** [fjodor-rybakov/discord-nestjs#545]
Following your examples and docs, I tried to implement a command with the newly supported slash commands. However, the arguments passed to the handler, doesn't seem to resolve properly.

After running `!deploy` once the bot has started, the command below also doesn't display/require the `song` param in Discord itself.

The following example will log (interaction, undefined) from the handler call.
```typescript
import { TransformPipe } from '@discord-nestjs/common';
import {
  Command,
  DiscordTransformedCommand,
  Payload,
  UsePipes,
  Param,
} from '@discord-nestjs/core';
import { Logger } from '@nestjs/common';
import { CommandInteraction } from 'discord.js';

// Dto Definition
class PlayDto {
  @Param({
    name: 'song',
    description:
      'Name or URL of song/playlist. Could be from (Youtube, Spotify, SoundCloud)',
    required: true,
  })
  song: string;
}

// Command
@Command({
  name: 'play',
  description: 'Plays a song',
})
@UsePipes(TransformPipe)
export class PlayCommand implements DiscordTransformedCommand<PlayDto> {
  private readonly logger = new Logger(PlayCommand.name);

  handler(@Payload() dto: PlayDto, interaction: CommandInteraction) {
    console.log({
      dto,
      interaction,
    });

    return 'Nice.';
  }
}
```

Please give me a shout if you need additional information!

**Comment by arelstone** [comment]
I know that this issue has been closed and solved. I had the same issue and discovered that I was missing `"useDefineForClassFields": true` in my tsconfig.json

**Comment by V-ed** [comment]
> I know that this issue has been closed and solved. I had the same issue and discovered that I was missing `"useDefineForClassFields": true` in my `tsconfig.json`

Yes, this solution has been added to the readme back then : https://github.com/fjodor-rybakov/discord-nestjs#i-created-dto-and-added-transformpipe-but-when-i-receive-response-to-the-command-the-dto-fields-are-missing

But having it surfaced here too isn't bad either :)
