### ISSUE TITLE
Inject DiscordClient

### ISSUE THREAD

**Issue by DaviZMelo** [fjodor-rybakov/discord-nestjs#581]
What is the best way for me to inject DiscordClient into a service without relying on an interaction?

**Comment by fjodor-rybakov** [comment]
Hi! Try this

```typescript
@Injectable()
class SomeService {
  constructor(
    private readonly discordClientProvider: DiscordClientProvider
  ) {}
}
```

**Comment by DaviZMelo** [comment]
That way I can only inject the DiscordProvider, is there any way I can inject the DiscordClient using multiple injections or without relying on importing it in the bot.module provider?

**Comment by fjodor-rybakov** [comment]
If you are using `DiscordProvider` within `bot.module`, then you do not need to import it. You can inject wherever you want. You cannot just inject the client into other modules without importing, since this violates the rules of nest. Alternatively, you can make `bot.module` global.
