### ISSUE TITLE
Transformed commands aren't registered if dto is in the same file

### ISSUE THREAD

**Issue by hoersamu** [fjodor-rybakov/discord-nestjs#584]
**Describe the bug**
Transformed commands are not registered with the bot if the dto is in the same file as the command.

**To Reproduce**
1. Start with the command sample
2. Create new transformed command `test.command.ts` (see source code below)
3. run npm build and npm start
4. type !deploy in discord

```
export class TestDto {
  @Param({
    name: 'song',
    description:
      'Name or URL of song/playlist. Could be from (Youtube, Spotify, SoundCloud)',
    required: true,
  })
  song: string;
}

@Command({
  name: 'test',
  description: 'Plays a song',
})
@UsePipes(TransformPipe)
export class TestCommand implements DiscordTransformedCommand<TestDto> {
  handler(@Payload() dto: TestDto, interaction: CommandInteraction): void {
    console.log('DTO', dto);
    console.log('Interaction', interaction);
  }
}
```

**Expected behavior**
Both the test command and the play command should be registered

**Desktop (please complete the following information):**

- OS: Win11
- Node: v16.13.0
- @discord-nestjs/common: 2.0.7
- @discord-nestjs/core: 2.1.5

**Comment by fjodor-rybakov** [comment]
Thanks for report! Fixed in next version
