### ISSUE TITLE
Missing command params

### ISSUE THREAD

**Issue by CorbalanLeandro** [fjodor-rybakov/discord-nestjs#590]
**Describe the bug**
I downloaded this repo to see if I was doing something wrong but I get the same error, when I execute the command `/play something` I get this on the console:
`~/node_modules\discord.js\src\structures\CommandInteractionOptionResolver.js:77
 throw new TypeError('COMMAND_INTERACTION_OPTION_NOT_FOUND', name);`

The content of the dto is undefined, if I set `required: false` I'm able to see it.
``` .json
{
  "song": undefined
}
```

**To Reproduce**

1. Download the repo and run  `npm i` on sample folder. (https://github.com/fjodor-rybakov/discord-nestjs/tree/master/packages/sample/command)
2. Set the discord token
3. Try to execute the command `/play something`
4. See error.

**Expected behavior**
Be able to see on the console.log the dto object.

**Desktop**

- OS: Windows
- node version: 16.6.0

**Comment by fjodor-rybakov** [comment]
Hi! I have not been able to reproduce your problem. Can you show your `tsconfig.json`?

**Comment by CorbalanLeandro** [comment]
https://github.com/fjodor-rybakov/discord-nestjs/blob/master/packages/sample/command/tsconfig.json
Is this one, I tried to use your sample and I get the same error

**Comment by CorbalanLeandro** [comment]
Maybe is a lack of permissions on the bot?

**Comment by fjodor-rybakov** [comment]
Your steps to reproduce are not giving the expected result. I checked the sample and it works. Can you show what's stored in `DiscordCommandProvider`?

**Comment by fjodor-rybakov** [comment]
And show what printed in output

**Comment by CorbalanLeandro** [comment]
![image](https://user-images.githubusercontent.com/70921636/142279603-82752c06-08cc-4ce5-845d-e6f1733491bc.png)
I don't know what a `DiscordCommandProvider` is? 😅

**Comment by fjodor-rybakov** [comment]
Show the log from the beginning (including the logging of the slash command)

**Comment by fjodor-rybakov** [comment]
Inject `DiscordCommandProvider` in your service and just print `this.discordCommandProvider.getAllCommands()` in on ready event

**Comment by CorbalanLeandro** [comment]
It's all, `npm run start:dev`
I printed out that, and I get an empty array

**Comment by fjodor-rybakov** [comment]
> It's all, from the beginning , `npm run start:dev` I printed out that, and I get an empty array

Judging by the logs you do not declare commands. If you have declared commands, but for some reason they are not visible, then try to explicitly set them in `commands` option. If you are using the sample command from the repository, then I'm not sure if you are using it correctly. Are you writing message `!deploy` before using slash commands?

Please read the documentation again.

**Comment by CorbalanLeandro** [comment]
Yes, I deployed the commands with `!deploy`, I get to see the commands on discord, but they are not accepting the input. 
I cloned your repository, I runned `npm i`, `npm run start:dev` and then `!deploy`.
