### ISSUE TITLE
Sending message direct to the channel is displaying interface error

### ISSUE THREAD

**Issue by janisha** [fjodor-rybakov/discord-nestjs#601]
**Describe the bug**
Interface is not complete and error is thrown when user tries to send a direct message to the discord channel from the system.

**To Reproduce**

    @Injectable()
    export class DiscordBroadcastService {
    
     constructor(private readonly discordProvider: DiscordClientProvider) {}
      
      sendMessage(channel: string, message: string) {
        this.discordProvider.getClient().channels.cache.get(channel).send(message);
      }    
    }

**this.discordProvider.getClient().channels.cache.get(channel)** does not return interface for send message and it displays error. 
It can be overridden by adding **//@ts-ignore** above the method and it will work, but the interface is not friendly.

     sendMessage(channel: string, message: string) {
        // @ts-ignore
        this.discordProvider.getClient().channels.cache.get(channel).send(message);
      }

**Comment by fjodor-rybakov** [comment]
`discord-nestjs` uses types from `discord.js` package. Please write problem with types [here](https://github.com/discordjs/discord.js/issues).
