### ISSUE TITLE
DTO - Param default value on optional fields

### ISSUE THREAD

**Issue by AntonyGarand** [fjodor-rybakov/discord-nestjs#602]
Hey!
Good job on the project, I love it 😁
A small annoyance I'm dealing with the DTO's is that there is no way to provide a default value for optional arguments.
This means I have to manually assign a default wherever I use the DTO, instead of only using it.

**Is your feature request related to a problem? Please describe.**
No, more of a minor annoyance.

**Describe the solution you'd like**
Adding a `default` argument on the `@Param` decorator.
```typescript
@Param({
  description: "Response visibility", 
  required: true, 
  type: ParamType.INTEGER,
  default: ResponseVisibility.Ephemeral, 
})
```

I'm more than happy to implement it if this is something that would get merged.

Thanks!

**Comment by fjodor-rybakov** [comment]
Hey! Good idea! I think it would be better not to add the parameter, but just add value initialization.

```typescript
@Param({
  description: "Response visibility", 
  required: true, 
  type: ParamType.INTEGER,
})
visibility = ResponseVisibility.Ephemeral;
```

It is very easy to add this feature by changing the transform pipe

**Comment by AntonyGarand** [comment]
I think both approaches are not mutually exclusive.
At the moment, simply having `= default` works and resolves my issue but I can think of certain advanced cases where the default value might need be computed.
In these cases, it would be good to have a default argument which can be a callback and contain the state of the answers, as it wouldn't be possible to use the default value.

Ex:
```typescript
@Param({
  description: "Response visibility", 
  required: true, 
  type: ParamType.INTEGER,
  default: (interaction, answers)=> interaction.author.isAdmin && answers.someCondition ? ResponseVisibility.Ephemeral : ResponseVisibility.Public, 
})
```

**Comment by fjodor-rybakov** [comment]
Added in 2.0.11 version `@discord-nestjs/common`

**Comment by fjodor-rybakov** [comment]
I don't think it's worth adding any logic to the DTO. Add your own pipe, which will update the DTO fields depending on your conditions.
