### ISSUE TITLE
(types): ApplicationCommandNumberOptionBase is not extending base properly

### ISSUE THREAD

**Issue by MufassirShaw** [fjodor-rybakov/discord-nestjs#617]
**Describe the bug**
There seems to be an issue in (@discordjs/builders) one of the peer dependency of discord.js. 

**To Reproduce**

1. `yarn add discord-nestjs`
2. `yarn start:dev` 
3. You should see an error like this 
![image](https://user-images.githubusercontent.com/30889549/147490643-8d2bce0f-e6ad-4cfd-92a3-3327e790175f.png)

**Desktop (please complete the following information):**

- OS: Windows10
- Version:
  discord.js: `^13.4.0`
  @discord-nestjs/common: `^2.0.12`
  @discord-nestjs/core: `^2.1.8`
  
**Workaround**
Downgrading `discord.js` from `^13.4.0` to `13.3.1` worked for me. For further details check [this issue](https://github.com/discordjs/builders/issues/67).

I hope this helps :)

**Comment by fjodor-rybakov** [comment]
Use `yarn add @discord-nestjs/core discord.js`  instead `yarn add discord-nestjs`. This issue has nothing to do with `discord-nestjs` package, so bring it to the appropriate repository (@discordjs/builders). Thanks!
