### ISSUE TITLE
Add deprecation notice for discord-nestjs

### ISSUE THREAD

**Issue by geisterfurz007** [fjodor-rybakov/discord-nestjs#652]
**Describe the bug**
Not strictly a bug but it's closer than a feature request; when searching for `nestjs discord` online, one stumbles over [discord-nestjs](https://www.npmjs.com/package/discord-nestjs#Installation) on NPM which hasn't been updated in 7 months. Only through clicking the link to this repository I found out that this is still maintained and has been split into smaller packages. The package should have a [deprecation notice](https://docs.npmjs.com/deprecating-and-undeprecating-packages-or-package-versions), linking to the maintained packages to avoid the appearance of an unmaintained package.

**To Reproduce**

1. Search "nestjs discord" on Google -> `discord-nestjs` is listed; `@discord-nestjs/core` or any other isn't
2. Click on [the NPM link](https://www.npmjs.com/package/discord-nestjs)
3. See the package is not deprecated or has any reference to the newer version of the project

**Expected behavior**
The NPM page shows a deprecation notice linking to [the core module](https://www.npmjs.com/package/@discord-nestjs/core) like [node-uuid does](https://www.npmjs.com/package/node-uuid).

**Screenshots**

![grafik](https://user-images.githubusercontent.com/26303198/154797298-df15b913-0eef-4a4b-b9b2-b0a40d99ae6d.png)

![grafik](https://user-images.githubusercontent.com/26303198/154797312-9beaa1c9-c617-4dc5-a244-70376aa1e759.png)

**Additional context**
*No further context*

**Comment by fjodor-rybakov** [comment]
Done
