### ISSUE TITLE
Slash command permissions

### ISSUE THREAD

**Issue by Kealman** [fjodor-rybakov/discord-nestjs#653]
Hey, thanks for this great repo!

I have a question or a feature request idk :)

Is there a way to set a slash command permission on deploy? Like this
https://discordjs.guide/interactions/slash-command-permissions.html#user-permissions

I think it should be in the CommandOptions
```javascript
@Command({
  name: 'command',
  description: 'command',
  permissions: [
   {
    id: '224617799434108928',
    type: 'USER',
    permission: false,
  }
],
})
```

**Comment by fjodor-rybakov** [comment]
Hi! Thanks for feedback.

If this is set in the decorator, then how, for example, to determine for which guild this will work?

**Comment by Nirator78** [comment]
I got the same request :)
