### ISSUE TITLE
Local guild testing hits daily limit, can I update instead of remove & register?

### ISSUE THREAD

**Issue by TheFlash787** [fjodor-rybakov/discord-nestjs#682]
**Describe the bug**
While developing the bot, I'm locally registering the commands in the guild -- opposed to globally, as this makes testing a lot easier and quicker as changes are instant.

I'm noticing however that I'm quickly hitting the daily registering limit that Discord has created which is 200 commands, from my bot restarting in watch mode.

Is it possible to update existing slash commands with Discord NestJS opposed to removing commands and then re-registering them? Am I doing something wrong (screenshot below) for this?

Does it already update but the `removeCommandsBefore` option causes it to re-register instead?

**To Reproduce**

1. Register your bot, and the command files used.
2. Develop your bot while testing, where NestJS will recompile after every save.
3. After a while of testing, you will hit the daily command registering limit and your commands will no longer register.

**Expected behavior**
I would like to be able to continue developing without running into Discord's Rate Limiter, through existing commands being updated rather than re-registered.

**Screenshots**
![image](https://user-images.githubusercontent.com/25883284/160686740-813d7f70-411d-499a-b844-25d3c5e1e30b.png)

**Comment by fjodor-rybakov** [comment]
Hi! You can use `allowFactory` option and register slash commands when needed.

```typescript
allowFactory: (message) =>
              message.author.bot && message.content === '!deploy',
```
