### ISSUE TITLE
Support Interaction Modals

### ISSUE THREAD

**Issue by TheFlash787** [fjodor-rybakov/discord-nestjs#690]
**Describe the feature**
Discord recently introduced interaction modals that work similar to other interactions in Discord -- and it'd be great to be able to register these with Discord NestJS, for use inside and outside of commands.

**Additional context**
A package has been made which adds some integration with DiscordJS and modals (as DiscordJS doesn't fully support them) and this may be of use: https://www.npmjs.com/package/discord-modals

![image](https://user-images.githubusercontent.com/25883284/161456642-30113b48-de21-48f7-8f76-c1ff1684ee0f.png)

**Comment by willjleong** [comment]
@[TheFlash787](https://github.com/TheFlash787) This would be awesome, and should be quite easy to add. In the mean time I've been using a workaround in the BotGateway constructor that works and allows me to subscribe to 'modalSubmit' with the `discord-modals` package. Kind of hacky but works well for now. 

```typescript
import { InjectDiscordClient, On, Once, UseGuards } from '@discord-nestjs/core';
import { Injectable, Logger } from '@nestjs/common';
// import discordModals from 'discord-modals';
import { InteractionTypes, ModalSubmitInteraction } from 'discord-modals';
import {
  ButtonInteraction,
  Client,
  Guild,
  Message,
  TextChannel,
} from 'discord.js';

@Injectable()
export class BotGateway {
  private readonly logger = new Logger(BotGateway.name);

  constructor(
    @InjectDiscordClient()
    private readonly client: Client,
    private setupService: SetupService,
    private buttonInteractionService: ButtonInteractionService,
    private helpService: HelpService,
  ) {
    this.client.ws.on('INTERACTION_CREATE', (data) => {
      if (!data.type) return;

      // MODAL_SUBMIT_INTERACTION_TYPE is the number 5
      switch (data.type) {
        case 5:
          this.logger.log(`Got a MODAL_SUBMIT ${data}`);
          this.client.emit(
            'modalSubmit',
            new ModalSubmitInteraction(this.client, data),
          );
          break;
      }
    });
  }

  @Once('ready')
  onReady(): void {
    this.logger.log(`Bot ${this.client.user.tag} was started!`);
  }

  @On('modalSubmit')
  async onModalSubmit(modal: ModalSubmitInteraction): Promise<void> {
    this.logger.log(`Modal ${modal.customId} submit`);
    await modal.deferReply({ ephemeral: true });
  }

  @On('error')
  onError(e: any): void {
    this.logger.log(`Received Error ${e}`);
  }
}

```

If I have some free time I'll create a PR for adding optional modal support to this package.

**Comment by arelstone** [comment]
Any update on this?

**Comment by fjodor-rybakov** [comment]
> @[TheFlash787](https://github.com/TheFlash787) This would be awesome, and should be quite easy to add. In the mean time I've been using a workaround in the `BotGateway` constructor that works and allows me to subscribe to 'modalSubmit' with the `discord-modals` package. Kind of hacky but works well for now!
> 
> ```ts
> import { InjectDiscordClient, On, Once, UseGuards } from '@discord-nestjs/core';
> import { Injectable, Logger } from '@nestjs/common';
> // import discordModals from 'discord-modals';
> import { InteractionTypes, ModalSubmitInteraction } from 'discord-modals';
> import {
>   ButtonInteraction,
>   Client,
>   Guild,
>   Message,
>   TextChannel,
> } from 'discord.js';
> 
> @Injectable()
> export class BotGateway {
>   private readonly logger = new Logger(BotGateway.name);
> 
>   constructor(
>     @InjectDiscordClient()
>     private readonly client: Client,
>     private setupService: SetupService,
>     private buttonInteractionService: ButtonInteractionService,
>     private helpService: HelpService,
>   ) {
>     this.client.ws.on('INTERACTION_CREATE', (data) => {
>       if (!data.type) return;
> 
>       // MODAL_SUBMIT_INTERACTION_TYPE is the number 5
>       switch (data.type) {
>         case 5:
>           this.logger.log(`Got a MODAL_SUBMIT ${data}`);
>           this.client.emit(
>             'modalSubmit',
>             new ModalSubmitInteraction(this.client, data),
>           );
>           break;
>       }
>     });
>     this.client.on('modalSubmit', async (modal: ModalSubmitInteraction) => {
>       this.logger.log(`Modal ${modal.customId} submit`);
>       await modal.deferReply({ ephemeral: true });
>     });
>   }
> 
>   @Once('ready')
>   onReady(): void {
>     this.logger.log(`Bot ${this.client.user.tag} was started!`);
>   }
> 
>   @On('error')
>   onError(e: any): void {
>     this.logger.log(`Received Error ${e}`);
>   }
> }
> ```
> 
> If I have some free time I'll create a PR for adding optional modal support to this package.

Can you make pr?
