### ISSUE TITLE
Slash Commands not registering parameters

### ISSUE THREAD

**Issue by simonmartyr** [fjodor-rybakov/discord-nestjs#701]
**Describe the bug**
When configuring a slash command with a DTO using `DiscordTransformedCommand`. The command does not appear to register the arguments.
Attempt to replicate the setup of the [example repo](https://github.com/fjodor-rybakov/discord-nestjs/tree/master/packages/sample/command), however was also not successful. 

**To Reproduce**

1. Create a `DiscordTransformedCommand`
2. Attempt to use slash command.
3. See no option for input. 

**Expected behavior**
The slash command in the discord application would ask for the expected DTO content.

**Screenshots**
![Screenshot 2022-04-18 203630](https://user-images.githubusercontent.com/1190774/163857871-55a1899f-a7c0-483e-bc6d-869a2a98ae9d.png)

**version info**

 - @discord-nestjs/common:  3.0.6
 - @discord-nestjs/core: 3.0.6 
- @nestjs/common 8.4.3
- @nestjs/core 8.4.3
- class-transformer 0.5.1
- reflect-metadata 0.1.13

**Additional context**

command.ts

```typescript
import { TransformPipe } from '@discord-nestjs/common';
import {
  Command,
  DiscordTransformedCommand,
  TransformedCommandExecutionContext,
  UsePipes,
  Payload,
} from '@discord-nestjs/core';
import { Injectable } from '@nestjs/common';
import { checkDto } from './check.dto';

@Injectable()
@Command({
  name: 'makevote',
  description: 'cast a vote for a member',
})
@UsePipes(TransformPipe)
export class MakeVote implements DiscordTransformedCommand<checkDto> {
  handler(
    @Payload() dto: checkDto,
    { interaction }: TransformedCommandExecutionContext,
  ): string {
    console.log(dto);
    console.log('Interaction', interaction);
    return `List with music...${dto.name}`;
  }
```

check.dto.ts

```typescript
import { Param, ParamType } from '@discord-nestjs/core';

export class checkDto {

  @Param({ description: 'User name', required: true, name: 'who' })
  name: string;

  @Param({
    description: 'User age',
    required: true,
    type: ParamType.INTEGER,
    name: 'age',
  })
  age: number;
}
```

additionally, here are my intents:

```typescript
        intents: [
          Intents.FLAGS.GUILDS,
          Intents.FLAGS.GUILD_MESSAGES,
          Intents.FLAGS.DIRECT_MESSAGES,
          Intents.FLAGS.GUILD_MEMBERS,
        ],
```

**Comment by fjodor-rybakov** [comment]
Did you set `"useDefineForClassFields": true` in your `tsconfig.json`? https://github.com/fjodor-rybakov/discord-nestjs/tree/master/packages/core#:~:text=Before%20you%20start%20using%2C%20set%20useDefineForClassFields%20to%20true%20in%20your%20tsconfig.json.

**Comment by simonmartyr** [comment]
That was it! My bad. 
Thank you so much for the quick response.

**Comment by jgreens** [comment]
Thank you @fjodor-rybakov – I ran into the same issue and this resolved it.
