### ISSUE TITLE
Discord.js v13 needs guildId in permissions

### ISSUE THREAD

**Issue by Arkmind** [fjodor-rybakov/discord-nestjs#720]
**Describe the bug**
Since Discord.js V13 all permissions needs a guildId whatever it's a global or a guild slash command

**To Reproduce**

1. Install last Discord.js version > 13.0
1. Write a new permission on your discord config
2. Nothing more

**Expected behavior**
An error should occur in the nestjs console

**Screenshots**
![image](https://user-images.githubusercontent.com/16468131/167166445-cd43cf7e-93bf-4fbc-9527-5e0c73027242.png)

***Stacktrace**
```
/srv/discord.limit-gif/node_modules/discord.js/src/managers/ApplicationCommandPermissionsManager.js:377
    if (!guildId) throw new Error('GLOBAL_COMMAND_PERMISSIONS');
                        ^
Error [GLOBAL_COMMAND_PERMISSIONS]: Permissions for global commands may only be fetched or modified by providing a GuildResolvable or from a guild's application command manager.
    at ApplicationCommandPermissionsManager._validateOptions (/srv/discord.limit-gif/node_modules/discord.js/src/managers/ApplicationCommandPermissionsManager.js:377:25)
    at ApplicationCommandPermissionsManager.set (/srv/discord.limit-gif/node_modules/discord.js/src/managers/ApplicationCommandPermissionsManager.js:162:41)
    at RegisterCommandService.<anonymous> (/srv/discord.limit-gif/node_modules/@discord-nestjs/core/src/services/register-command.service.ts:236:37)
    at Generator.next (<anonymous>)
    at /srv/discord.limit-gif/node_modules/@discord-nestjs/core/dist/services/register-command.service.js:20:71
    at new Promise (<anonymous>)
    at __awaiter (/srv/discord.limit-gif/node_modules/@discord-nestjs/core/dist/services/register-command.service.js:16:12)
    at /srv/discord.limit-gif/node_modules/@discord-nestjs/core/src/services/register-command.service.ts:230:53
    at Array.map (<anonymous>)
    at RegisterCommandService.<anonymous> (/srv/discord.limit-gif/node_modules/@discord-nestjs/core/src/services/register-command.service.ts:229:32)
```

**Environment**
- OS: Ubuntu 20.04.4 LTS
- Discord.js: ^13.6.0
- @discord-nestjs/core: ^3.1.0
- @discord-nestjs/common: ^3.1.0

**Additional context**
Adding an mandatory guildId Type string containing the guildId on Interface `SlashCommandPermissions` and sending it to discord.js

**Comment by fjodor-rybakov** [comment]
Probably worth thinking about how to do it better

**Comment by fjodor-rybakov** [comment]
> Seems to be induced by this commit [2c41af5](https://github.com/fjodor-rybakov/discord-nestjs/commit/2c41af578578aec404631b15ad557f86a6950885)

I don't know why but unfortunately code in this commit doesn't work

**Comment by Arkmind** [comment]
I've found this on the Discord.js documentation
https://discordjs.guide/interactions/slash-commands.html#global-commands
Seems like you have to use different methods to register global and guild slash commands, permissions will then be updated by the type of command (global where update could take up to 1h or guild who is instant)

**Comment by Arkmind** [comment]
So after a few more researches i've finally understood why permissions by command ain't working anymore
Here's the [Discord.js post](https://discord.com/channels/222078108977594368/769862166131245066/968986201216409620) :
> Discord is rolling out Slash Command Permissions v2 to all guilds - **it is no longer possible to set slash command > permission overrides**
> > Blog post: https://discord.com/blog/slash-commands-permissions-discord-apps-bots
> > Documentation PR: https://github.com/discord/discord-api-docs/pull/4830

> Permissions v2 removes access to the endpoint for bots to set permission overrides on commands.
> Server admins are now responsible for managing slash command permissions themselves via the server settings.
> `default_permission` is now split into `default_member_permissions` for guilds, and `dm_permission` for DMs. 

Thanks for the replies, I'm closing this issue ! 💯

**Comment by TheFlash787** [comment]
> So after a few more researches i've finally understood why permissions by command ain't working anymore Here's the [Discord.js post](https://discord.com/channels/222078108977594368/769862166131245066/968986201216409620) :
> 
> > Discord is rolling out Slash Command Permissions v2 to all guilds - **it is no longer possible to set slash command > permission overrides**
> > > Blog post: https://discord.com/blog/slash-commands-permissions-discord-apps-bots
> > > Documentation PR: [discord/discord-api-docs#4830](https://github.com/discord/discord-api-docs/pull/4830)
> 
> > Permissions v2 removes access to the endpoint for bots to set permission overrides on commands.
> > Server admins are now responsible for managing slash command permissions themselves via the server settings.
> > `default_permission` is now split into `default_member_permissions` for guilds, and `dm_permission` for DMs.
> 
> Thanks for the replies, I'm closing this issue ! 💯

@fjodor-rybakov Isn't this still an issue with the current DiscordModule implementation? The issue was closed, but a solution in the module wasn't identified.

When using guild commands, with the permissions defined in the module factory as shown in the documentation, the following error occurs. Don't we need to make sure we're supporting Permissions v2?

![image](https://user-images.githubusercontent.com/25883284/170849301-0b0c0612-fff2-4abe-8802-9c6cf04e3f2c.png)

**Comment by fjodor-rybakov** [comment]
> > So after a few more researches i've finally understood why permissions by command ain't working anymore Here's the [Discord.js post](https://discord.com/channels/222078108977594368/769862166131245066/968986201216409620) :
> > > Discord is rolling out Slash Command Permissions v2 to all guilds - **it is no longer possible to set slash command > permission overrides**
> > > > Blog post: https://discord.com/blog/slash-commands-permissions-discord-apps-bots
> > > > Documentation PR: [discord/discord-api-docs#4830](https://github.com/discord/discord-api-docs/pull/4830)
> > 
> > 
> > > Permissions v2 removes access to the endpoint for bots to set permission overrides on commands.
> > > Server admins are now responsible for managing slash command permissions themselves via the server settings.
> > > `default_permission` is now split into `default_member_permissions` for guilds, and `dm_permission` for DMs.
> > 
> > 
> > Thanks for the replies, I'm closing this issue ! 💯
> 
> @fjodor-rybakov Isn't this still an issue with the current DiscordModule implementation? The issue was closed, but a solution in the module wasn't identified and therefore the entire permissions system doesn't work anymore in the module.
> 
> When using guild commands, with the permissions defined in the module factory as shown in the documentation, the following error occurs. Don't we need to make sure we're supporting Permissions v2 for both guild and command permissions.
> 
> With the new system, the permissions we specify should be the command's default permissions.
> 
> ![image](https://user-images.githubusercontent.com/25883284/170849301-0b0c0612-fff2-4abe-8802-9c6cf04e3f2c.png)

Wait for this https://github.com/discordjs/discord.js/pull/7857 please

**Comment by TheFlash787** [comment]
> > > So after a few more researches i've finally understood why permissions by command ain't working anymore Here's the [Discord.js post](https://discord.com/channels/222078108977594368/769862166131245066/968986201216409620) :
> > > > Discord is rolling out Slash Command Permissions v2 to all guilds - **it is no longer possible to set slash command > permission overrides**
> > > > > Blog post: https://discord.com/blog/slash-commands-permissions-discord-apps-bots
> > > > > Documentation PR: [discord/discord-api-docs#4830](https://github.com/discord/discord-api-docs/pull/4830)
> > > 
> > > 
> > > > Permissions v2 removes access to the endpoint for bots to set permission overrides on commands.
> > > > Server admins are now responsible for managing slash command permissions themselves via the server settings.
> > > > `default_permission` is now split into `default_member_permissions` for guilds, and `dm_permission` for DMs.
> > > 
> > > 
> > > Thanks for the replies, I'm closing this issue ! 💯
> > 
> > 
> > @fjodor-rybakov Isn't this still an issue with the current DiscordModule implementation? The issue was closed, but a solution in the module wasn't identified and therefore the entire permissions system doesn't work anymore in the module.
> > When using guild commands, with the permissions defined in the module factory as shown in the documentation, the following error occurs. Don't we need to make sure we're supporting Permissions v2 for both guild and command permissions.
> > With the new system, the permissions we specify should be the command's default permissions.
> > ![image](https://user-images.githubusercontent.com/25883284/170849301-0b0c0612-fff2-4abe-8802-9c6cf04e3f2c.png)
> 
> Wait for this [discordjs/discord.js#7857](https://github.com/discordjs/discord.js/pull/7857) please

Looks like this has all been approved and merged. 🙂

**Comment by fjodor-rybakov** [comment]
> > > > So after a few more researches i've finally understood why permissions by command ain't working anymore Here's the [Discord.js post](https://discord.com/channels/222078108977594368/769862166131245066/968986201216409620) :
> > > > > Discord is rolling out Slash Command Permissions v2 to all guilds - **it is no longer possible to set slash command > permission overrides**
> > > > > > Blog post: https://discord.com/blog/slash-commands-permissions-discord-apps-bots
> > > > > > Documentation PR: [discord/discord-api-docs#4830](https://github.com/discord/discord-api-docs/pull/4830)
> > > > 
> > > > 
> > > > > Permissions v2 removes access to the endpoint for bots to set permission overrides on commands.
> > > > > Server admins are now responsible for managing slash command permissions themselves via the server settings.
> > > > > `default_permission` is now split into `default_member_permissions` for guilds, and `dm_permission` for DMs.
> > > > 
> > > > 
> > > > Thanks for the replies, I'm closing this issue ! 💯
> > > 
> > > 
> > > @fjodor-rybakov Isn't this still an issue with the current DiscordModule implementation? The issue was closed, but a solution in the module wasn't identified and therefore the entire permissions system doesn't work anymore in the module.
> > > When using guild commands, with the permissions defined in the module factory as shown in the documentation, the following error occurs. Don't we need to make sure we're supporting Permissions v2 for both guild and command permissions.
> > > With the new system, the permissions we specify should be the command's default permissions.
> > > ![image](https://user-images.githubusercontent.com/25883284/170849301-0b0c0612-fff2-4abe-8802-9c6cf04e3f2c.png)
> > 
> > 
> > Wait for this [discordjs/discord.js#7857](https://github.com/discordjs/discord.js/pull/7857) please
> 
> Looks like this has all been approved and merged. 🙂

Everything seems to be working now
