### ISSUE TITLE
Component interaction

### ISSUE THREAD

**Issue by wolffparkinson** [fjodor-rybakov/discord-nestjs#730]
**Is your feature request related to a problem? Please describe.**
Support for Button and Select Menu interaction

**Describe the solution you'd like**
I could not find if there was supported component and autocomplete interactions.
Implementing them in a similar fashion as Slash commands would be very much desirable

**Describe alternatives you've considered**
Register gateway event for `interactionCreate` and matching against a collection of components is what I am doing currently. But having inherent support for guards, pipes, decorators etc would be very much desirable.

**Comment by fjodor-rybakov** [comment]
Hi! Thanks for suggestion! Options that were missing I added. 

So far I see no point in creating a separate decorator for autocomplete and component, since the logic behind this decorator is very small. Use the `@On` decorator + `guard` which will check autocomplete for example.
