### ISSUE TITLE
Register commands manually

### ISSUE THREAD

**Issue by ydhn** [fjodor-rybakov/discord-nestjs#786]
**Is your feature request related to a problem? Please describe.**
I'm deploying my discord bot in the cloud with multiple instances.  
Somehow, I made a Redis-based command-ignoring logic so that not every instance handles one request.
The problem is that the current `registerCommandOptions` only supports triggering `RegisterCommandService` by discord message, so it is hard to suppress every instance registering new commands. This is especially problematic when the `removeCommandsBefore` flag is on.

**Describe the solution you'd like**
1. Expose `RegisterCommandService` in the `DiscordModule` and let it trigger by manual (for example, HTTP request by admin, not with discord message such as `!deploy`)

**Describe alternatives you've considered**
if registerCommandOptions.allowFactory support Promise, I can add a ignore logic based on the caching layer(like Redis) so that I can trigger only one (not all of the instances)

**Additional context**
nothing.

**Comment by fjodor-rybakov** [comment]
Hi! The `allowFactory` method allow you register does not require mandatory registration by discord message. Inside `allowFactory` method you can do anything, including HTTP requests. 

If your configuration is large enough, you can use `useClass` instead of `useFactory`

**Comment by ydhn** [comment]
@fjodor-rybakov Hi, I couldn't understand how `allowFactory` can handle HTTP requests. 
the function is judging whether an incoming discord message is for trigger or not, isn't it?

**Comment by fjodor-rybakov** [comment]
I don't think it's a good idea move `RegisterCommandService` outside. I added a trigger option, which will allow you to call slash command registration whenever you want.

**Comment by ydhn** [comment]
Thanks for your quick support, @fjodor-rybakov !  
I like the way you implemented it. nice.
