### ISSUE TITLE
Guard context receives message array instead of message

### ISSUE THREAD

**Issue by DimosthenisK** [fjodor-rybakov/discord-nestjs#79]
**Describe the bug**
The guard receives an array of messages instead of a single message, like it is described in the docs.

**To Reproduce**
1. Create a simple guard
2. Console.log or use a breakpoint to view the context parameter

**Expected behavior**
The context should be a single message as described in the docs

**Screenshots**
![image](https://user-images.githubusercontent.com/32791127/101283915-163c7a00-37e6-11eb-9bae-d805698d0884.png)
![image](https://user-images.githubusercontent.com/32791127/101283920-205e7880-37e6-11eb-8f76-2ec552af8f1f.png)

**Desktop (please complete the following information):**
 - OS: Windows

**Comment by fjodor-rybakov** [comment]
Incorrect documentation. `context` always is array because the number of handler arguments can be multiple. Will be fixed in the next update.

**Comment by fjodor-rybakov** [comment]
Fixed in v0.3.6
