### ISSUE TITLE
Failed to connect to discord on startup without failing app.

### ISSUE THREAD

**Issue by itsinprog** [fjodor-rybakov/discord-nestjs#818]
**Describe the bug**
Upon startup the discord connection within the module failed and it didn't stop the application from considering it started "successfully".

**To Reproduce**
Do anything that stops the discord api connection from succeeding, and then start the app.

**Expected behavior**
The module initialization should fail and nest should not start successfully.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Mac
- Browser  N/A
- Version v4

**Additional context**

> `[31m[Nest] 17 - [39m07/28/2022, 5:25:03 PM [31m ERROR[39m [38;5;3m[ClientService] [39m[31mFailed to connect to Discord API[39m`
``[32m[Nest] 17 - [39m07/28/2022, 5:25:03 PM [32m LOG[39m [38;5;3m[NestApplication] [39m[32mNest application successfully started[39m[38;5;3m +10ms[39m``

**Comment by fjodor-rybakov** [comment]
Set `failOnLogin: true`
