### ISSUE TITLE
Impossible to use with nestjs-telegraf

### ISSUE THREAD

**Issue by Simkav** [fjodor-rybakov/discord-nestjs#838]
**Describe the bug**
Usage discord-nestjs with nestjs-telegraf will throw error

**Dependencies**
@discord-nestjs/core": "^4.1.1"
discord.js": "^14.2.0"
telegraf": "^4.8.6"
nestjs-telegraf": "^2.6.0"

**To Reproduce**
1. Register TelegrafModule with options in app module
2. Register DiscordModule with options in app module
3. Register any discord handler decorator like @Once('ready')

**Expected behavior**
I expect it to work

**Desktop**
- OS: Ubuntu
- Version 22.04
- Node: 16.15.0

**Additional context**
Stacktrace:
> TypeError: Cannot read properties of undefined (reading 'allowEvents')
gateway_1  |     at /home/node/app/node_modules/@discord-nestjs/core/src/explorers/middleware/middleware.explorer.ts:44:4
gateway_1  |     at Array.filter (<anonymous>)
gateway_1  |     at MiddlewareExplorer.<anonymous> (/home/node/app/node_modules/@discord-nestjs/core/src/explorers/middleware/middleware.explorer.ts:35:25)
gateway_1  |     at Generator.next (<anonymous>)
gateway_1  |     at /home/node/app/node_modules/@discord-nestjs/core/dist/explorers/middleware/middleware.explorer.js:17:71
gateway_1  |     at new Promise (<anonymous>)
gateway_1  |     at __awaiter (/home/node/app/node_modules/@discord-nestjs/core/dist/explorers/middleware/middleware.explorer.js:13:12)
gateway_1  |     at MiddlewareExplorer.applyMiddleware (/home/node/app/node_modules/@discord-nestjs/core/dist/explorers/middleware/middleware.explorer.js:49:16)
gateway_1  |     at EventExplorer.<anonymous> (/home/node/app/node_modules/@discord-nestjs/core/src/explorers/event/event.explorer.ts:64:43)
gateway_1  |     at Generator.next (<anonymous>)

**Comment by fjodor-rybakov** [comment]
Hi! Can you provide minimum reproduction repo?

**Comment by fjodor-rybakov** [comment]
If the problem is not solved, reopen the issue again
