### ISSUE TITLE
Specify permission needed to launch slash command

### ISSUE THREAD

**Issue by mrsolarius** [fjodor-rybakov/discord-nestjs#865]
Hi there,
actually, when we want to specify permission to a command, we need to use a guard that act after the launch of slash command. But with discord API, we can specify in the slash description that we don't want a command for some permission. And then the slash command will not just not appear in the slash menu if you don't have the permission.

The ideal solution for me will be to specify the permission for the slash command directly inside @command() something that could look like that : 
```typescript
@Command({
  name: "mute",
  description: "command to temporary mute somone",
  permision:["KickMembers","BanMembers"]
})
```
As we have discussed with @jonasschultheiss on your discord, this one of the first thing we want as a developer after discover this incredibly good way of creating slash command. :smiley:

**Comment by fjodor-rybakov** [comment]
Hi! You can set permission via defaultMemberPermission option https://github.com/fjodor-rybakov/discord-nestjs/blob/master/packages/core/src/decorators/command/base-command-options.ts#L17

**Comment by mrsolarius** [comment]
It already exist!
Woo, this is soo sweet :)
