### ISSUE TITLE
slash command /play (from example) no dto

### ISSUE THREAD

**Issue by ChristopherLMiller** [fjodor-rybakov/discord-nestjs#879]
**Describe the bug**
Tryign to implement slash commands in own project, copied the play command to test, when executing the command dto is empty object.

**Expected behavior**
expected output to discord should be the song passed in, get undefined, console log just says '''DTO PlayDto {}'''

**Additional context**

**Comment by fjodor-rybakov** [comment]
This question has been asked before. Try search it. Also check [docs](https://github.com/fjodor-rybakov/discord-nestjs/tree/master/packages/core#:~:text=%E2%9A%A0%EF%B8%8F,tsconfig.json.)
