### ISSUE TITLE
TransformPipe support for user type

### ISSUE THREAD

**Issue by Harpush** [fjodor-rybakov/discord-nestjs#888]
Currently `TransformPipe` doesn't respect `@Param({ type: ParamType.USER })`. The property gets filled with the user id due to this line in the source code: https://github.com/fjodor-rybakov/discord-nestjs/blob/master/packages/common/src/pipe/transform.pipe.ts#L42.
The proposed solution is to introduce support when the type is user to do `interaction.options.getUser(name ?? property, required)`.

**Comment by fjodor-rybakov** [comment]
Hi! Can you create a pull request?

**Comment by Harpush** [comment]
@fjodor-rybakov Isn't it a breaking change?

**Comment by fjodor-rybakov** [comment]
> @fjodor-rybakov Isn't it a breaking change? And what's the contribution guidelines?

Without breaking change. Make commits by [conventional of commits](https://www.conventionalcommits.org/en/v1.0.0/), because the next version chosen based on them.

**Comment by Harpush** [comment]
@fjodor-rybakov Just to make sure - currently specifing param of type user returns string (user id) and after the change it will return a user object. Correct? How can I make it non breaking?

**Comment by fjodor-rybakov** [comment]
> @fjodor-rybakov Just to make sure - currently specifing param of type user returns string (user id) and after the change it will return a user object. Correct? How can I make it non breaking?

Yep, make it as `feat` without breaking change
