### ISSUE TITLE
Add an option to create message collectors instead of only creating channel ones

### ISSUE THREAD

**Issue by LcsGa** [fjodor-rybakov/discord-nestjs#922]
**Is your feature request related to a problem? Please describe.**
I'm writing a command:
- It sends a button that can be clicked by any user
- On each click, the bot reacts by sending some ephemeral messages to the user who clicked
- As the user keeps clicking, the button won't be easily reachable anymore
- The user rewrites the command to create a new button
=> On a new click, we receive a DiscordApiError due to the fact that the collector is on channels only
```sh
node_modules/@discordjs/rest/src/lib/handlers/SequentialHandler.ts:497
                                throw new DiscordAPIError(data, 'code' in data ? data.code : data.error, status, method, url, requestData);
          ^
DiscordAPIError[40060]: Interaction has already been acknowledged.
    at SequentialHandler.runRequest (/home/lucas/dev/fishing-bot/node_modules/@discordjs/rest/src/lib/handlers/SequentialHandler.ts:497:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at SequentialHandler.queueRequest (/home/lucas/dev/fishing-bot/node_modules/@discordjs/rest/src/lib/handlers/SequentialHandler.ts:198:11)
    at REST.request (/home/lucas/dev/fishing-bot/node_modules/@discordjs/rest/src/lib/REST.ts:343:20)
    at ButtonInteraction.deferReply (/home/lucas/dev/fishing-bot/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:69:5)
```
It is due to channel collectors returning component interactions for any component within that channel.

**Describe the solution you'd like**
add on option to do `<Message>.createMessageComponentCollector(…)` in addition to `<Channel>.createMessageComponentCollector(…)` (currently the only option)

**Describe alternatives you've considered**
The only alternative I would have would be sending many / commands to replace that button, which is not what I'd like

**Comment by LcsGa** [comment]
The use of `<Channel>.createMessageComponentCollector(…)` can be found in this file https://github.com/fjodor-rybakov/discord-nestjs/blob/1d44ef1b3af48ff735ffcac3a5e95f8efd186fb3/packages/core/src/explorers/collector/strategy/interaction-collector.strategy.ts#L40

**Comment by fjodor-rybakov** [comment]
Will be fixed in 5 version

**Comment by fjodor-rybakov** [comment]
Duplicate https://github.com/fjodor-rybakov/discord-nestjs/issues/868
