### ISSUE TITLE
Guild Commands

### ISSUE THREAD

**Issue by fishuke** [fjodor-rybakov/discord-nestjs#943]
**Describe the bug**
We can add "forGuild" param for making all the commands for a guild. But what if i only want a specific command to be a guild command?

**Expected behavior**
Like discord.js i should be able to customize each command to make it a guild command.
https://discord.com/developers/docs/interactions/application-commands#application-command-object

**Comment by fishuke** [comment]
@fjodor-rybakov

**Comment by fjodor-rybakov** [comment]
> @fjodor-rybakov

Sorry for late reply, will be added in the next (5) version

**Comment by fishuke** [comment]
Great! We are using this module in a verified bot that has over 6k servers. Check here: https://stalk.gg
I would appreciate it if I can help with development...

**Comment by fjodor-rybakov** [comment]
Ok, i can do it in the minor version, if you need to quickly

**Comment by fishuke** [comment]
Would be great so i can use global commands along with guild commands...

**Comment by fishuke** [comment]
Also registering commands when sharding is a little bit tricky. So i manually trigger the register in first shard... This can be solved with adding a bool variable to wheter sync or not...

**Comment by fjodor-rybakov** [comment]
> Also registering commands when sharding is a little bit tricky. So i manually trigger the register in first shard... This can be solved with adding a bool variable to wheter sync or not...

Can you make pr with enhancement?

**Comment by fishuke** [comment]
I did not update the module but i think i can try...

**Comment by fishuke** [comment]
@fjodor-rybakov Now there is a bigger problem, there is no command option choice localizations, see: https://discord.com/developers/docs/interactions/application-commands#application-command-object-application-command-option-choice-structure

**Comment by fjodor-rybakov** [comment]
> @fjodor-rybakov Now there is a bigger problem, there is no command option choice localizations, see: https://discord.com/developers/docs/interactions/application-commands#application-command-object-application-command-option-choice-structure

https://github.com/fjodor-rybakov/discord-nestjs/blob/master/packages/core/src/decorators/command/base-command-options.ts#L12

**Comment by fishuke** [comment]
@fjodor-rybakov thats not what i am talking about we need command option choice localization check the link that i sent please

**Comment by fishuke** [comment]
@fjodor-rybakov any luck?

**Comment by fishuke** [comment]
Another problem how to add channel param for command?

Discord option types: 

NAME | VALUE | NOTE
-- | -- | --
SUB_COMMAND | 1 |  
SUB_COMMAND_GROUP | 2 |  
STRING | 3 |  
INTEGER | 4 | Any integer between -2^53 and 2^53
BOOLEAN | 5 |  
USER | 6 |  
CHANNEL | 7 | Includes all channel types + categories
ROLE | 8 |  
MENTIONABLE | 9 | Includes users and roles
NUMBER | 10 | Any double between -2^53 and 2^53
ATTACHMENT | 11 | attachment object

discord-nestjs Option Types:
```
export declare enum ParamType {
    STRING = 0,
    INTEGER = 1,
    BOOLEAN = 2,
    USER = 3,
    ROLE = 4,
    MENTIONABLE = 5,
    NUMBER = 6,
    ATTACHMENT = 7
}
```

**Comment by fishuke** [comment]
@fjodor-rybakov another note command param localizations arent working...
