### ISSUE TITLE
guard  receive undefined context 

### ISSUE THREAD

**Issue by LucaXiang** [fjodor-rybakov/discord-nestjs#95]
**Describe the bug**
if use multi guard, the second canActive function will receive undefined context.
![image](https://user-images.githubusercontent.com/22201628/102024502-ab191780-3d92-11eb-8908-55266bea2960.png)
i think is because reduce function should return prevData for next call.
![image](https://user-images.githubusercontent.com/22201628/102024543-f2070d00-3d92-11eb-8e48-e6074ee6d70c.png)

**Comment by fjodor-rybakov** [comment]
Fixed in v0.3.6
