### ISSUE TITLE
Support graceful failure/retries

### ISSUE THREAD

**Issue by wallopthecat** [fjodor-rybakov/discord-nestjs#96]
**Is your feature request related to a problem? Please describe.**
When discord api is down, the nestjs app cannot start, and hangs in the bootstrapping modules phase, with no error message and no indication of what went wrong.

**Describe the solution you'd like**
Timeouts and retries, or add an option to allow failures (discord api is non-critical for operation of other parts of this app)

**Describe alternatives you've considered**

**Additional context**
Confirmed removing discord module import from my app.module.ts allowed the app to start again without hanging here:
```
[RouterExplorer] Mapped {/health, GET} route +0ms
```

EDIT: just realize that this is probably an option of the underlying lib, discord.js, but had already posted here. Looking for a solution to non-blocking module startup either way

**Comment by elderapo** [comment]
Any plans regarding this issue? It seems like a must-have. Having the whole app crash/not start because discord API is down is pretty bad.

**Comment by fjodor-rybakov** [comment]
> Any plans regarding this issue? It seems like a must-have. Having the whole app crash/not start because discord API is down is pretty bad.

Will be added in release 1.0.0
