### ISSUE TITLE
InteractionEvent decorator is not exported

### ISSUE THREAD

**Issue by kodze** [fjodor-rybakov/discord-nestjs#989]
**Describe the bug**
When I try to import InteractionEvent, I have an error message saying "TS2305: Module '"@discord-nestjs/core"' has no exported member 'InteractionEvent'." (it's the same for Handler). 
I tried to create application command with args.

**To Reproduce**

1. Just use "import {Command, InteractionEvent, Handler} from '@discord-nestjs/core';"

**Expected behavior**
Importing decorators

**Screenshots**
![image](https://user-images.githubusercontent.com/6042072/218454448-ed3a3ee1-cba2-4065-8813-06b034480016.png)

**Desktop (please complete the following information):**

- OS: Ubunutu

**Additional context**
I run on the latest version of discord-nestjs: 5.2.1

**Comment by fjodor-rybakov** [comment]
Hi! Make sure you have installed `@discord-nestjs/core` package. If the `@discord-nestjs/core` is really installed, then check(in node_modules) that you have the latest version 5.2.1.

P.S. 
Perhaps you are install two different versions of `@discord-nestjs/core` and the older version overrides the new one?

**Comment by kodze** [comment]
Hello, thanks for your answer! 

It was indeed an issue with the wrong version of the lib + wrong version of the discord js lib.

Thanks a lot!
